server:
  port: 8819
spring:
  cloud:
    config:
      uri: https://config.3o3.co.kr
  config:
    import: 'configserver:'
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;DATABASE_TO_LOWER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE
    username: sa
    driver-class-name: org.h2.Driver
jasypt:
  encryptor:
    bean: jasyptConfigEncryptor

szs:
  kms:
    key-id:
    algorithm:
    secret:

test: # ENC(??? ?)